{% set name = "rules" %}
{% set version = "3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rules-{{ version }}.tar.gz
  sha256: f01336218f4561bab95f53672d22418b4168baea271423d50d9e8490d64cb27a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - rules
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/dfunckt/django-rules
  summary: Awesome Django authorization, without the database
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
